# Primer parcial Computación blanda

importamos las liberias para crear la red neuronal

In [118]:
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation,Dropout
import numpy as np

### Set de datos

Estos son los posibles estados que van a tener los sensores del robot.

Orden de los sensores {0,1,2,3,4,5,6}

los valores del vector se corresponden a la distncia que marcan los sensores

In [119]:
data = np.array([[0.23,1,1,1,1,1],
                 [0.23,0.23,1,1,1,1],
                 [0.12,0.12,1,1,1,1],
                 [1,1,1,1,1,1],
                 [1,1,0.12,0.12,1,1],
                 [1,1,0.23,0.23,1,1],
                 [1,1,1,1,0.23,0.23],
                 [1,1,1,1,1,0.23],
                 [1,1,1,1,0.12,0.12],
                 [1,1,1,0.23,1,1],
                 [1,1,0.23,1,1,1],
                 [1,1,1,0.12,0.12,1]])


print(data)
print('\nCantidad de combinaciones de los sensores: ',len(data))

[[0.23 1.   1.   1.   1.   1.  ]
 [0.23 0.23 1.   1.   1.   1.  ]
 [0.12 0.12 1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.  ]
 [1.   1.   0.12 0.12 1.   1.  ]
 [1.   1.   0.23 0.23 1.   1.  ]
 [1.   1.   1.   1.   0.23 0.23]
 [1.   1.   1.   1.   1.   0.23]
 [1.   1.   1.   1.   0.12 0.12]
 [1.   1.   1.   0.23 1.   1.  ]
 [1.   1.   0.23 1.   1.   1.  ]
 [1.   1.   1.   0.12 0.12 1.  ]]

Cantidad de combinaciones de los sensores:  12


Estas son las posibles salidas a los estados de los sensores, es la forma en que se van  a mover los motores.

Orden de los motores: {a,b}, a-> motor derecho, b->motor izquierdo 

Los valores del vector se corresponden a la direccion de los motores.

In [120]:
movMotores = np.array([
                       [1,1,0,1],#[1 , 0.5],
                       [1,1,0,1],#[1 , 0.5],
                       [1,1,0,0],#[1 , 0],
                       [1,1,1,1],#,[1 , 1],
                       [0,0,1,0],#[0 , 0.75],
                       [1,0,1,1],#[0.6 , 1],
                       [0,1,1,1],#[0.5 , 1],
                       [0,1,1,1],#[0.5 , 1],
                       [0,0,1,1],#[0 , 1],
                       [0,0,1,1],#[0 , 1],
                       [0,0,1,1],#[0 , 1],
                       [0,0,0,1]])#[0 , 0.5],])

print(movMotores)
print('\nLos movimientos de los motores: ', len(movMotores))

[[1 1 0 1]
 [1 1 0 1]
 [1 1 0 0]
 [1 1 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 1 1]
 [0 0 1 1]
 [0 0 0 1]]

Los movimientos de los motores:  12


Creamos el modelo de la red neuronal

In [147]:
model = Sequential()

Agregamos las capas 

In [148]:
model.add(Dense(6, activation='relu', input_dim=6))

model.add(Dense(15, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(5, activation='relu'))
#model.add(Dense(15, activation='relu'))
#model.add(Dropout(0.5))
#model.add(Dense(3, activation='relu'))
model.add(Dense(4, activation='softmax'))
#model.summary()

Compilamos el modelo

In [149]:
ad = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
model.compile(loss='categorical_crossentropy',
              optimizer = ad,
              metrics=['accuracy'])

Ahora entrenamos el modelo

In [150]:
train = model.fit(data, movMotores,
          epochs=200,
          batch_size=5)#128

Epoch 1/200
12/12 [==============================] - 1s 73ms/step - loss: 3.3981 - acc: 0.0833
Epoch 2/200
12/12 [==============================] - 0s 515us/step - loss: 3.3810 - acc: 0.0833
Epoch 3/200
12/12 [==============================] - 0s 839us/step - loss: 3.3696 - acc: 0.0833
Epoch 4/200
12/12 [==============================] - 0s 653us/step - loss: 3.3609 - acc: 0.0833
Epoch 5/200
12/12 [==============================] - 0s 796us/step - loss: 3.3512 - acc: 0.0833
Epoch 6/200
12/12 [==============================] - 0s 998us/step - loss: 3.3462 - acc: 0.0833
Epoch 7/200
12/12 [==============================] - 0s 867us/step - loss: 3.3413 - acc: 0.0833
Epoch 8/200
12/12 [==============================] - 0s 815us/step - loss: 3.3372 - acc: 0.0833
Epoch 9/200
12/12 [==============================] - 0s 974us/step - loss: 3.3328 - acc: 0.0833
Epoch 10/200
12/12 [==============================] - 0s 724us/step - loss: 3.3283 - acc: 0.0833
Epoch 11/200
12/12 [====================

Ahora hacemos una revision del modelo

In [151]:
score = model.evaluate(data, movMotores, batch_size=5)

12/12 [==============================] - 0s 23ms/step


In [152]:
print(score)

[2.683247129122416, 0.5000000111758709]


In [153]:
model.predict(np.array([[1,1,1,0.12,0.12,1]]))

array([[0.0764404 , 0.04590555, 0.05438476, 0.82326925]], dtype=float32)